lakehouse_dbt:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('DBT_SPARK_HOST', 'spark-thrift') }}"
      port: "{{ env_var('DBT_SPARK_PORT', '10000') | as_number }}"
      user: "{{ env_var('DBT_SPARK_USER', 'root') }}"
      schema: default
      threads: 2
      connect_timeout: 60
      connect_retries: 5

    local:
      type: spark
      method: session
      host: localhost
      schema: default
      threads: 2

